import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    backgroundColor: "#FFCB05",
    padding: 10,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    padding: 10,
    alignItems: "center",
    // borderWidth: 0,
    // shadowOpacity: 0,
    borderBottomWidth: 2,
    borderBottomColor: "#E0E0E0",
  },
  logo: {
    width: "100%",
    height: 100,
    resizeMode: "contain",
  },
  infoContainer: {
    backgroundColor: "#FFCB05",
    borderRadius: 10,
    padding: 10,
    alignItems: "center",
    margin: 10,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderColor: "#0000FF",
    borderWidth: 2,
    borderRadius: 10,
  },
  pokemonImage: {
    width: 100,
    height: 100,
    resizeMode: "contain",
    flex: 0,
    width: 80,
    height: 80,
    marginRight: 10,
  },
  NombrePokemon: {
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 5,
  },
  textContainer: {
    flex: 1,
    padding: 10,
  },
  features: {
    fontSize: 16,
    color: "#000",
    textAlign: "left",
    alignSelf: "flex-start",
    width: "100%",
  },
  sectionContainer: {
    backgroundColor: "#FFCB05",
    borderRadius: 10,
    padding: 10,
    margin: 10,
    borderColor: "#0000FF",
    borderWidth: 2,
    borderRadius: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
  type: {
    fontSize: 16,
    color: "#000",
    marginBottom: 5,
  },
  move: {
    fontSize: 16,
    color: "#000",
    marginBottom: 5,
  },
});
